config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  get '/families/feature' => 'families#feature'
  resources :users
  resources :families
  resources :families, only: [:show] do
    resources :roles, only: [:new, :create, :destroy]
    resources :boards, only: [:edit]
    resources :users, only: [:show]
  end
  resources :tags, only: [:create, :update]
  resources :boards, only: [:update]
  resources :boards, only: [:show] do
    resources :tags, only: [:edit]
  end


  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  post '/signout' => 'sessions#destroy'
  get '/auth/github/callback' => 'sessions#create'
end

app/models/family.rb
class Family < ActiveRecord::Base
    has_many :roles
    has_many :users, through: :roles
    has_secure_password :validations => false
    has_one :board
    validates :last_name, presence: true
    scope :largest_family, ->{ joins(:roles).group('families.id').order('COUNT(families.id) DESC').first }
    
    def self.largest_family_from_iteration
        families_count = self.all.collect { |family| 
            family.roles.count
        }
        largest_number_of_people = families_count.max
        largest_family = self.all.find { |family| family.roles.count == largest_number_of_people }
    end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:index, :show]

    def index
        @families = Family.all
    end

    def feature
        @family = Family.largest_family
    end

    def show
        @family = Family.find(params[:id])
        @tag = Tag.new
    end

    def new
        @family = Family.new
    end

    def create
        @family = Family.new(family_params)

        if @family.valid?
            board = Board.create()
            @family.board = board

            if params[:header] != ""
                board.header = params[:header]
                board.save
            end

            @family.save

            role = Role.new(title: params[:title])
            role.family = @family
            role.user = current_user
            role.save

            redirect_to @family
        else
            render 'families/new'
        end
    end

    def edit
        authorize_user_for_family_edit
        @family = Family.find(params[:id])
    end

    private

    def family_params
        params.require(:family).permit(:last_name, :password, :password_confirmation)
    end

    def authorize_user_for_family_edit
        family = Family.find(params[:id])
        if !(current_user.parent_of_this_family?(family))
            redirect_to family
        end
    end
end

app/views/families/edit.html.erb
<h1><%= @family.last_name %> Family</h1>

<% @family.users.each do |user| %>
    <% role = user.my_role_in_this_family(@family) %>
    <% if user != current_user %>
        <li><%= user.first_name %> (<%= role.title %>) <%= link_to "Disown", "/families/#{@family.id}/roles/#{role.id}", method: :delete %></li>
    <% end %>
<% end %>

app/views/families/feature.html.erb
<h2><%= @family.last_name %> Family has the largest family </h2>

app/views/families/index.html.erb
<h1>Families</h1>

<ul>
<% @families.each do |family| %>
    <li><%= link_to family.last_name, family_path(family) %></li>
<% end %>
</ul>

<%= link_to "Create a New Family", "/families/new" %>

app/views/families/new.html.erb
<%= render partial: 'application/errors', locals: { object: @family } %>

<%= form_for @family do |f| %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br>

    (Password is optional)<br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <br><br>

    <%= label_tag "header", "Create Header for your family" %>
    <%= text_field_tag "header" %>
    <br><br>

    <%= label_tag "title", "Choose your title:" %>
    <%= select_tag "title", raw("<option>Mom</option><option>Dad</option><option>Eldest</option><option selected='selected'>Middle</option><option>Youngest</option>") %>
    <br>

    <%= f.submit %>
<% end %>

app/views/families/show.html.erb
<h1><%= @family.last_name %> Family</h1>

<ul>
    <% @family.roles.each do |role| %>
        <li><%= link_to role.user.first_name, "/families/#{@family.id}/users/#{role.user.id}" %> <%= "(#{role.title})" %></li>
    <% end %>
</ul>

<% if logged_in? %>
    <% if @family.users.include?(current_user) %>
        <% role = Role.find_by(user_id: current_user.id, family_id: @family.id) %>
        <%= link_to "Leave Family", "/families/#{@family.id}/roles/#{role.id}", method: :delete %><br>

        <%= link_to "Edit Family", "/families/#{@family.id}/edit" if current_user.parent_of_this_family?(@family) %>

        <%= render partial: 'boards/board', locals: { board: @family.board, family: @family } %>
        
        <%= render partial: 'tags/form', locals: { tag: @tag, board: @family.board } %> 
        <br>
        
    <% else %>
        <%= link_to "Join the #{@family.last_name} Family", new_family_role_path(@family.id) %>
    <% end %>
<% else %>
    <h4><%= link_to "Sign Up", "/users/new" %> or <%= link_to "Sign In", "/signin" %> to join Family!</h4>
<% end %>