config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  get '/families/feature' => 'families#feature'
  resources :users
  resources :families
  resources :families, only: [:show] do
    resources :roles, only: [:new, :create, :destroy]
    resources :boards, only: [:edit]
    resources :users, only: [:show]
  end
  resources :tags, only: [:create, :update]
  resources :boards, only: [:update]
  resources :boards, only: [:show] do
    resources :tags, only: [:edit]
  end


  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  post '/signout' => 'sessions#destroy'
  get '/auth/github/callback' => 'sessions#create'
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :roles
    has_many :families, through: :roles

    has_secure_password
    validates :email, presence: true
    validates :first_name, presence: true
    validates :email, uniqueness: true
    scope :parents_for_this_family, ->(family){ joins(:roles).where(roles: { title: ["Mom", "Dad"] }).where(roles: { family_id: family.id }) }
 
    def self.find_or_create_by_omniauth(auth_hash)
        oauth_email = auth_hash["info"]["email"]
        if user = User.find_by(:email => oauth_email)
            return user
        else
            user = User.create(:email => oauth_email, :password => SecureRandom.hex)
        end
    end

    def my_role_in_this_family(family)
        Role.find_by(user_id: self.id, family_id: family.id)
    end

    def parent_of_this_family?(family)
        User.parents_for_this_family(family).include?(self)
    end

    def create_tag_for_this_familys_board(family, content)
        tag = Tag.new(content: content)
        tag.board = family.board
        tag.user = self
        tag.save
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, :authorize_user_for_edit, only: [:edit, :update]

    def new
        require_logout
        @user = User.new
    end

    def index
        @users = User.all
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render 'users/new'
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        if @user.save
            redirect_to @user
        else
            render 'users/edit'
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :first_name, :password, :password_confirmation)
    end

    def require_logout
        if logged_in?
            redirect_to current_user
        end
    end

    def authorize_user_for_edit
        user = User.find(params[:id])
        if current_user != user
            redirect_to current_user
        end
    end
end

app/views/users/edit.html.erb
<h3>Change First Name</h3>

<%= render partial: 'application/errors', locals: { object: @user } %>

<%= form_for @user do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br>

    <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>People</h1>

<ul>
<% @users.each do |user| %>
    <li><%= link_to user.first_name, user_path(user) %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<%= render partial: 'application/errors', locals: { object: @user } %>

<%= form_for @user do |f| %>

    <%= f.label :email %>
    <%= f.text_field :email %><br>

    <%= f.label :first_name %>
    <%= f.text_field :first_name, :value => '' %><br>

    <%= f.label :password %>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>
    <%= "Your Profile:" if current_user == @user %>
    <%= @user.first_name %>
</h2>

<%= link_to "Edit Profile", "/users/#{@user.id}/edit" if current_user == @user %>

<h2>Families:</h2>

<ul>
    <% @user.families.each do |family| %>
        <li><%= link_to family.last_name, family_path(family) %></li>
    <% end %>
</ul>