config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  get '/families/feature' => 'families#feature'
  resources :users
  resources :families
  resources :families, only: [:show] do
    resources :roles, only: [:new, :create, :destroy]
    resources :boards, only: [:edit]
    resources :users, only: [:show]
  end
  resources :tags, only: [:create, :update]
  resources :boards, only: [:update]
  resources :boards, only: [:show] do
    resources :tags, only: [:edit]
  end


  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  post '/signout' => 'sessions#destroy'
  get '/auth/github/callback' => 'sessions#create'
end

app/models/role.rb
class Role < ActiveRecord::Base
    belongs_to :user
    belongs_to :family
    validates :user_id, :uniqueness => {:scope => :family_id}
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
    before_action :require_login

    def new
        @family = Family.find(params[:family_id])
        @role = Role.new
    end

    def create
        @family = Family.find(params[:family_id])
        @role = Role.new(role_params)

        if !!@family.password_digest
            if !@family.authenticate(params[:family][:password])
                flash[:notice] = "Wrong password"
                return render 'roles/new'
            end
        end

        @role.user_id = current_user.id
        @role.family_id = @family.id
        if @role.save
            redirect_to @family
        else
            render 'roles/new'
        end 
    end
    
    def destroy
        family = Family.find(params[:family_id])
        if !(family.users.include?(current_user))
            redirect_to family and return
        end

        Role.find(params[:id]).destroy
        redirect_to family
    end

    private

    def role_params
        params.permit(:title)
    end
end

app/views/roles/new.html.erb
<%= flash[:notice] %><br>

<%= render partial: 'application/errors', locals: { object: @role } %>

<%= form_for @family, method: :post, url: family_roles_path(@family) do |f| %>
    
    <% if !!@family.password_digest %>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <br>
    <% end %>

    <%= label_tag "title", "Choose your title:" %>
    <%= select_tag "title", raw("<option>Mom</option><option>Dad</option><option>Eldest</option><option selected='selected'>Middle</option><option>Youngest</option>") %>
    <br>

    <%= f.submit "Join Family" %>
<% end %>